// This file is autogenerated by build-project-images script.
// Please do not edit this file manually. Any changes will be overwritten.
// To regenerate: npm run build-images

export type ProjectUrls = { src: string; compressedSrc: string };

import cckbSrc from '/src/assets/project-images/cckb-x2.webp';
import cckbCompressedSrc from '/src/assets/project-images/cckb-x1.webp';
import codebreakerSrc from '/src/assets/project-images/codebreaker-x2.webp';
import codebreakerCompressedSrc from '/src/assets/project-images/codebreaker-x1.webp';
import klinkySrc from '/src/assets/project-images/klinky-x2.webp';
import klinkyCompressedSrc from '/src/assets/project-images/klinky-x1.webp';
import mapSlicerSrc from '/src/assets/project-images/mapSlicer-x2.webp';
import mapSlicerCompressedSrc from '/src/assets/project-images/mapSlicer-x1.webp';
import pokematchSrc from '/src/assets/project-images/pokematch-x2.webp';
import pokematchCompressedSrc from '/src/assets/project-images/pokematch-x1.webp';
import reposSrc from '/src/assets/project-images/repos-x2.webp';
import reposCompressedSrc from '/src/assets/project-images/repos-x1.webp';
import tntLaserWorksSrc from '/src/assets/project-images/tntLaserWorks-x2.webp';
import tntLaserWorksCompressedSrc from '/src/assets/project-images/tntLaserWorks-x1.webp';

const cckb: ProjectUrls = { src: cckbSrc, compressedSrc: cckbCompressedSrc };

const codebreaker: ProjectUrls = { src: codebreakerSrc, compressedSrc: codebreakerCompressedSrc };

const klinky: ProjectUrls = { src: klinkySrc, compressedSrc: klinkyCompressedSrc };

const mapSlicer: ProjectUrls = { src: mapSlicerSrc, compressedSrc: mapSlicerCompressedSrc };

const pokematch: ProjectUrls = { src: pokematchSrc, compressedSrc: pokematchCompressedSrc };

const repos: ProjectUrls = { src: reposSrc, compressedSrc: reposCompressedSrc };

const tntLaserWorks: ProjectUrls = { src: tntLaserWorksSrc, compressedSrc: tntLaserWorksCompressedSrc };

export const urls = {
  'cckb': cckb,
  'codebreaker': codebreaker,
  'klinky': klinky,
  'mapSlicer': mapSlicer,
  'pokematch': pokematch,
  'repos': repos,
  'tntLaserWorks': tntLaserWorks,
} as const;

export type ProjectKey = keyof typeof urls;
