// This file is autogenerated by build-project-images script.
// Please do not edit this file manually. Any changes will be overwritten.
// To regenerate: npm run build-images

export type ProjectUrls = { src: string; compressedSrc: string };

import pokematchSrc from '/src/assets/project-images/pokematch.webp';
import pokematchCompressedSrc from '/src/assets/project-images/pokematch-tiny.webp';
import reposSrc from '/src/assets/project-images/repos.webp';
import reposCompressedSrc from '/src/assets/project-images/repos-tiny.webp';

const pokematch: ProjectUrls = { src: pokematchSrc, compressedSrc: pokematchCompressedSrc };

const repos: ProjectUrls = { src: reposSrc, compressedSrc: reposCompressedSrc };

export const urls = {
  'pokematch': pokematch,
  'repos': repos,
} as const;

export type ProjectKey = keyof typeof urls;
