name: deploy

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test:
    name: Lint and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.node-version'
          cache: 'npm'
      - name: Lint and Test
        run: |
          npm ci
          npx playwright install --with-deps
          npm run lint
          npm run test
          npm run build

  upload:
    name: Upload to GitHub Pages
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.node-version'
          cache: 'npm'
      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs

  deploy:
    name: Deploy to GitHub Pages
    needs: upload
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.pages-deployment.outputs.page_url }}
    steps:
      - uses: actions/deploy-pages@v4
        id: pages-deployment

  audit:
    name: Lighthouse Audit
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.node-version'
          cache: 'npm'
      - run: |
          npm ci
          npm run lighthouse
